services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: db
      POSTGRES_USER: db
      TZ: UTC
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persists database data

volumes:
  postgres_data:
  redis_data: